version: '3'
services:

  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=finch
    ports:
      - "15432:5432"

  finch:
    image: 481193184231.dkr.ecr.us-west-2.amazonaws.com/lh-finch:latest
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8081:8080"